USE CS340318
SELECT E.LNAME, M.LNAME, Z.REVIEWED, Z.ENV_TYPE, Z.ACTION_DESC
FROM MAINFRAME Z JOIN ARCEMP E
ON Z.DEVID = E.ID
JOIN ARCEMP M
ON Z.MGNID = M.ID
UNION
SELECT E.LNAME, M.LNAME, W.REVIEWED, W.ENV_TYPE, W.PROJECT_NAME
FROM WEB W JOIN ARCEMP E
ON W.DEVID = E.ID
JOIN ARCEMP M
ON W.MGNID = M.ID
UNION
SELECT E.LNAME, M.LNAME, D.REVIEWED, D.ENV_TYPE, D.PROJECT_NAME
FROM DESKTOP D JOIN ARCEMP E
ON D.DEVID = E.ID
JOIN ARCEMP M
ON D.MGNID = M.ID;

