USE CS340318
SELECT Z.ID, Z.ACTION_DESC AS 'PROJECT NAME', Z.ENV_TYPE AS 'ENVIRONMENT', CONCAT(E.LNAME, ', ', E.FNAME) AS 'DEVELOPER NAME', CONCAT(M.LNAME, ', ', M.FNAME) AS 'MANAGER NAME'
FROM MAINFRAME Z JOIN ARCEMP E
ON Z.DEVID = E.ID
JOIN ARCEMP M
ON Z.MGNID = M.ID
WHERE Z.ENV_TYPE = 1
UNION
SELECT W.ID, W.PROJECT_NAME AS 'PROJECT NAME', W.ENV_TYPE AS 'ENVIRONMENT', CONCAT(E.LNAME, ', ', E.FNAME) AS 'DEVELOPER NAME', CONCAT(M.LNAME, ', ', M.FNAME) AS 'MANAGER NAME'
FROM WEB W JOIN ARCEMP E
ON W.DEVID = E.ID
JOIN ARCEMP M
ON W.MGNID = M.ID
WHERE W.ENV_TYPE = 1
UNION
SELECT D.ID, D.PROJECT_NAME AS 'PROJECT NAME', D.ENV_TYPE AS 'ENVIRONMENT', CONCAT(E.LNAME, ', ', E.FNAME) AS 'DEVELOPER NAME', CONCAT(M.LNAME, ', ', M.FNAME) AS 'MANAGER NAME'
FROM DESKTOP D JOIN ARCEMP E
ON D.DEVID = E.ID
JOIN ARCEMP M
ON D.MGNID = M.ID
WHERE D.ENV_TYPE = 1

